# Generated by Django 5.2.8 on 2025-11-29 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=255)),
                ('hospital_name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hospital Staff',
                'db_table': 'hospital_staff',
            },
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_file', models.FileField(upload_to='medical_reports/%Y/%m/')),
                ('encrypted_file_key', models.TextField(blank=True, null=True)),
                ('scan_type', models.CharField(choices=[('MRI', 'MRI Scan'), ('CT', 'CT Scan'), ('Blood', 'Blood Test'), ('Xray', 'X-Ray'), ('Ultrasound', 'Ultrasound'), ('ECG', 'ECG'), ('Others', 'Others')], max_length=50)),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('patient_phone_match', models.CharField(blank=True, max_length=15, null=True)),
                ('patient_aadhaar_match', models.CharField(blank=True, max_length=4, null=True)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('requires_otp', models.BooleanField(default=True)),
                ('uploaded_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to='core.hospitalstaff')),
            ],
            options={
                'db_table': 'medical_reports',
                'ordering': ['-uploaded_date'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_summary', models.TextField()),
                ('abnormal_findings', models.JSONField(default=list)),
                ('risk_level', models.CharField(choices=[('Low', 'Low Risk'), ('Medium', 'Medium Risk'), ('High', 'High Risk')], max_length=20)),
                ('lifestyle_recommendations', models.JSONField(default=list)),
                ('doctor_visit_suggestion', models.TextField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(default='English', max_length=20)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='core.medicalreport')),
            ],
            options={
                'db_table': 'ai_analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('district', models.CharField(choices=[('Bagalkot', 'Bagalkot'), ('Ballari', 'Ballari'), ('Belagavi', 'Belagavi'), ('Bengaluru Rural', 'Bengaluru Rural'), ('Bengaluru Urban', 'Bengaluru Urban'), ('Bidar', 'Bidar'), ('Chamarajanagar', 'Chamarajanagar'), ('Chikkaballapur', 'Chikkaballapur'), ('Chikkamagaluru', 'Chikkamagaluru'), ('Chitradurga', 'Chitradurga'), ('Dakshina Kannada', 'Dakshina Kannada'), ('Davanagere', 'Davanagere'), ('Dharwad', 'Dharwad'), ('Gadag', 'Gadag'), ('Hassan', 'Hassan'), ('Haveri', 'Haveri'), ('Kalaburagi', 'Kalaburagi'), ('Kodagu', 'Kodagu'), ('Kolar', 'Kolar'), ('Koppal', 'Koppal'), ('Mandya', 'Mandya'), ('Mysuru', 'Mysuru'), ('Raichur', 'Raichur'), ('Ramanagara', 'Ramanagara'), ('Shivamogga', 'Shivamogga'), ('Tumakuru', 'Tumakuru'), ('Udupi', 'Udupi'), ('Uttara Kannada', 'Uttara Kannada'), ('Vijayapura', 'Vijayapura'), ('Yadgir', 'Yadgir')], max_length=100)),
                ('economic_status', models.CharField(choices=[('APL', 'Above Poverty Line'), ('BPL', 'Below Poverty Line')], max_length=10)),
                ('has_ration_card', models.BooleanField(default=False)),
                ('has_aadhaar', models.BooleanField(default=False)),
                ('aadhaar_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('disease_type', models.CharField(choices=[('Cardio', 'Cardiovascular'), ('Ortho', 'Orthopedic'), ('General', 'General Medicine'), ('Cancer', 'Oncology'), ('Neuro', 'Neurological'), ('Kidney', 'Renal'), ('Others', 'Others')], max_length=50)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_profiles',
            },
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='core.patientprofile'),
        ),
        migrations.CreateModel(
            name='ReportAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('VIEW', 'View'), ('DOWNLOAD', 'Download')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('access_granted', models.BooleanField(default=False)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='core.medicalreport')),
            ],
            options={
                'db_table': 'report_access_logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=255)),
                ('scheme_type', models.CharField(max_length=50)),
                ('eligibility_score', models.CharField(max_length=10)),
                ('why_eligible', models.TextField()),
                ('required_documents', models.JSONField(default=list)),
                ('apply_steps', models.JSONField(default=list)),
                ('language_output', models.CharField(default='English', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_results', to='core.patientprofile')),
            ],
            options={
                'db_table': 'scheme_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=49.0, max_digits=10)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_analysis_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
