# Generated by Django 5.2.8 on 2026-03-10 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_otp_verified_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('specialization', models.CharField(choices=[('General', 'General Medicine'), ('Cardio', 'Cardiology'), ('Neuro', 'Neurology'), ('Ortho', 'Orthopedics'), ('Hematology', 'Hematology'), ('Endocrinology', 'Endocrinology'), ('Nephrology', 'Nephrology / Renal'), ('Oncology', 'Oncology'), ('Pulmonology', 'Pulmonology'), ('Gastro', 'Gastroenterology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Others', 'Others')], default='General', max_length=100)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('hospital_affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(choices=[('Bagalkot', 'Bagalkot'), ('Ballari', 'Ballari'), ('Belagavi', 'Belagavi'), ('Bengaluru Rural', 'Bengaluru Rural'), ('Bengaluru Urban', 'Bengaluru Urban'), ('Bidar', 'Bidar'), ('Chamarajanagar', 'Chamarajanagar'), ('Chikkaballapur', 'Chikkaballapur'), ('Chikkamagaluru', 'Chikkamagaluru'), ('Chitradurga', 'Chitradurga'), ('Dakshina Kannada', 'Dakshina Kannada'), ('Davanagere', 'Davanagere'), ('Dharwad', 'Dharwad'), ('Gadag', 'Gadag'), ('Hassan', 'Hassan'), ('Haveri', 'Haveri'), ('Kalaburagi', 'Kalaburagi'), ('Kodagu', 'Kodagu'), ('Kolar', 'Kolar'), ('Koppal', 'Koppal'), ('Mandya', 'Mandya'), ('Mysuru', 'Mysuru'), ('Raichur', 'Raichur'), ('Ramanagara', 'Ramanagara'), ('Shivamogga', 'Shivamogga'), ('Tumakuru', 'Tumakuru'), ('Udupi', 'Udupi'), ('Uttara Kannada', 'Uttara Kannada'), ('Vijayapura', 'Vijayapura'), ('Yadgir', 'Yadgir')], default='Bengaluru Urban', max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Doctor Profiles',
                'db_table': 'doctor_profiles',
            },
        ),
    ]
