# Generated by Django 5.2.8 on 2026-03-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_doctorprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('General', 'General Medicine'), ('Cardio', 'Cardiology'), ('Neuro', 'Neurology'), ('Ortho', 'Orthopedics'), ('Hematology', 'Hematology'), ('Endocrinology', 'Endocrinology'), ('Nephrology', 'Nephrology / Renal'), ('Oncology', 'Oncology'), ('Pulmonology', 'Pulmonology'), ('Gastro', 'Gastroenterology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Gynecology', 'Gynecology'), ('Others', 'Others')], default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='disease_type',
            field=models.CharField(choices=[('Cardio', 'Cardiovascular'), ('Ortho', 'Orthopedic'), ('General', 'General Medicine'), ('Cancer', 'Oncology'), ('Neuro', 'Neurological'), ('Kidney', 'Renal'), ('Gynecology', 'Gynecology'), ('Others', 'Others')], max_length=50),
        ),
    ]
