# Generated by Django 5.2.8 on 2026-03-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_doctorprofile_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstaff',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
    ]
