# Generated by Django 5.2.8 on 2026-03-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hospitalstaff_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('General', 'General Medicine'), ('Cardio', 'Cardiology'), ('Neuro', 'Neurology'), ('Ortho', 'Orthopedics'), ('Hematology', 'Hematology'), ('Endocrinology', 'Endocrinology'), ('Nephrology', 'Nephrology / Renal'), ('Oncology', 'Oncology'), ('Pulmonology', 'Pulmonology'), ('Gastro', 'Gastroenterology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Gynecologist', 'Gynecologist'), ('Others', 'Others')], default='General', max_length=100),
        ),
    ]
